#!/usr/bin/env bash

set -u

sleep 2

# ─────────────────────────────
# IDLE DAEMON
# ─────────────────────────────

if ! pgrep -x hypridle >/dev/null; then
    hypridle &
fi

# ─────────────────────────────
# WAYBAR
# ─────────────────────────────

if ! pgrep -x waybar >/dev/null; then
    waybar &
fi

# ─────────────────────────────
# WALLPAPER
# ─────────────────────────────

sleep 1

$HOME/.config/hypr/scripts/wallpaper &

# ─────────────────────────────
# QUICKSHELL DOCK
# ─────────────────────────────

sleep 1

qs -c dock
